"""
NoDAW / MyAIPlug skin ecosystem for CoProducer.

Source of truth:
  D:\\Projects\\IMPORTANT BRAND STYLING FOR MYAIPLUG, NODAW, THEBEATMOB\\
    NoDAW_5_Theme_Ecosystem_Brand_Style.md
    MyAIPlug_Brand_Style.md  (Liquid Logic / Liquid Intelligence)

Qt needs solid hex - rgba surfaces are flattened onto each theme's BG.
"""

from __future__ import annotations

from typing import Any


def _flat(bg: str, r: int, g: int, b: int, a: float) -> str:
    """Composite translucent RGB over solid bg hex → solid hex."""
    bg = bg.lstrip("#")
    br, bg_, bb = int(bg[0:2], 16), int(bg[2:4], 16), int(bg[4:6], 16)
    a = max(0.0, min(1.0, a))
    rr = int(br * (1 - a) + r * a)
    gg = int(bg_ * (1 - a) + g * a)
    bb2 = int(bb * (1 - a) + b * a)
    return f"#{rr:02x}{gg:02x}{bb2:02x}"


def _muted(text: str, alpha: float = 0.55) -> str:
    t = text.lstrip("#")
    r, g, b = int(t[0:2], 16), int(t[2:4], 16), int(t[4:6], 16)
    # blend toward black for "muted" solid
    return _flat("#000000", r, g, b, alpha)


# ---------------------------------------------------------------------------
# Skin definitions (distinct - do not average)
# ---------------------------------------------------------------------------

SKINS: dict[str, dict[str, Any]] = {
    # CoProducer analyzer default - forensic / diagnostic (brand rec)
    "artifact-scan": {
        "id": "artifact-scan",
        "name": "Artifact / Radar Scan",
        "group": "NoDAW",
        "blurb": "Forensic diagnostics - ideal for analysis tools",
        "bg": "#03080a",
        "surface": _flat("#03080a", 4, 18, 22, 0.92),
        "elevated": _flat("#03080a", 8, 28, 32, 0.88),
        "hover": _flat("#03080a", 12, 40, 46, 0.9),
        "accent": "#00ffaa",
        "accent_soft": "#00d4ff",
        "accent_dim": "#00a878",
        "gold": "#9eff00",
        "success": "#00ffaa",
        "warning": "#ffb000",
        "error": "#ff4466",
        "text": "#dfffee",
        "muted": _muted("#dfffee", 0.52),
        "line": _flat("#03080a", 0, 255, 170, 0.20),
        "line_hover": _flat("#03080a", 0, 212, 255, 0.35),
        "score_excellent": "#00ffaa",
        "score_good": "#00d4ff",
        "score_fair": "#ffb000",
        "score_poor": "#ff4466",
    },
    "obsidian-glass": {
        "id": "obsidian-glass",
        "name": "Obsidian Glass",
        "group": "NoDAW",
        "blurb": "Flagship black glass - default ecosystem skin",
        "bg": "#000000",
        "surface": _flat("#000000", 8, 10, 14, 0.92),
        "elevated": _flat("#000000", 18, 20, 28, 0.88),
        "hover": _flat("#000000", 28, 30, 40, 0.9),
        "accent": "#22d3ee",
        "accent_soft": "#67e8f9",
        "accent_dim": "#0891b2",
        "gold": "#c8a24a",
        "success": "#10b981",
        "warning": "#f97316",
        "error": "#ef4444",
        "text": "#f5f5f5",
        "muted": _muted("#ffffff", 0.48),
        "line": _flat("#000000", 255, 255, 255, 0.12),
        "line_hover": _flat("#000000", 255, 255, 255, 0.22),
        "score_excellent": "#22d3ee",
        "score_good": "#10b981",
        "score_fair": "#f97316",
        "score_poor": "#ef4444",
    },
    "newton-antigravity": {
        "id": "newton-antigravity",
        "name": "Newton Antigravity",
        "group": "NoDAW",
        "blurb": "Surreal black/violet levitation - high concept",
        "bg": "#030003",
        "surface": _flat("#030003", 18, 8, 24, 0.88),
        "elevated": _flat("#030003", 28, 12, 40, 0.85),
        "hover": _flat("#030003", 40, 18, 56, 0.9),
        "accent": "#b56cff",
        "accent_soft": "#ff4fd8",
        "accent_dim": "#7c3aed",
        "gold": "#f7d774",
        "success": "#b56cff",
        "warning": "#f7d774",
        "error": "#ff4fd8",
        "text": "#f6f0ff",
        "muted": _muted("#f6f0ff", 0.58),
        "line": _flat("#030003", 180, 120, 255, 0.28),
        "line_hover": _flat("#030003", 255, 79, 216, 0.35),
        "score_excellent": "#b56cff",
        "score_good": "#ff4fd8",
        "score_fair": "#f7d774",
        "score_poor": "#ff6b9d",
    },
    "chromatic-nihilism": {
        "id": "chromatic-nihilism",
        "name": "Chromatic Nihilism",
        "group": "NoDAW",
        "blurb": "Aggressive neon - glitch / destructive energy",
        "bg": "#050005",
        "surface": _flat("#050005", 15, 0, 20, 0.9),
        "elevated": _flat("#050005", 28, 0, 36, 0.88),
        "hover": _flat("#050005", 40, 0, 50, 0.9),
        "accent": "#ff0080",
        "accent_soft": "#8000ff",
        "accent_dim": "#cc0066",
        "gold": "#00ffff",
        "success": "#00ffff",
        "warning": "#fff000",
        "error": "#ff0080",
        "text": "#ffffff",
        "muted": _muted("#ffffff", 0.55),
        "line": _flat("#050005", 255, 0, 128, 0.32),
        "line_hover": _flat("#050005", 0, 255, 255, 0.35),
        "score_excellent": "#00ffff",
        "score_good": "#ff0080",
        "score_fair": "#fff000",
        "score_poor": "#ff0080",
    },
    "crystal-prism": {
        "id": "crystal-prism",
        "name": "Crystal Prism",
        "group": "NoDAW",
        "blurb": "Premium luminous glass - future luxury",
        "bg": "#020008",
        "surface": _flat("#020008", 12, 8, 22, 0.88),
        "elevated": _flat("#020008", 20, 14, 36, 0.85),
        "hover": _flat("#020008", 32, 22, 52, 0.9),
        "accent": "#a78bfa",
        "accent_soft": "#00ffff",
        "accent_dim": "#7c3aed",
        "gold": "#ff4fd8",
        "success": "#00ffff",
        "warning": "#ff4fd8",
        "error": "#ff6b9d",
        "text": "#ffffff",
        "muted": _muted("#ffffff", 0.56),
        "line": _flat("#020008", 180, 220, 255, 0.28),
        "line_hover": _flat("#020008", 167, 139, 250, 0.4),
        "score_excellent": "#ffffff",
        "score_good": "#a78bfa",
        "score_fair": "#00ffff",
        "score_poor": "#ff4fd8",
    },
    # MyAIPlug Liquid Intelligence / Liquid Logic
    "liquid-logic": {
        "id": "liquid-logic",
        "name": "Liquid Logic",
        "group": "MyAIPlug",
        "blurb": "Liquid intelligence - cyan telemetry glass",
        "bg": "#020408",
        "surface": "#0a1520",
        "elevated": "#0e1c2a",
        "hover": "#132536",
        "accent": "#00d4ff",
        "accent_soft": "#00ffcc",
        "accent_dim": "#0066cc",
        "gold": "#00ff88",
        "success": "#00ff88",
        "warning": "#ff9500",
        "error": "#ff4466",
        "text": "#d8eeff",
        "muted": "#6d8faa",
        "line": _flat("#020408", 0, 180, 255, 0.18),
        "line_hover": _flat("#020408", 0, 212, 255, 0.35),
        "score_excellent": "#00d4ff",
        "score_good": "#00ffcc",
        "score_fair": "#ff9500",
        "score_poor": "#ff4466",
    },
    # Master NoDAW Cyber-HUD tokens (brand §4)
    "nodaw-cyber": {
        "id": "nodaw-cyber",
        "name": "NoDAW Cyber-HUD",
        "group": "NoDAW",
        "blurb": "Master Cyber-HUD - cyan/emerald pro panel language",
        "bg": "#020617",
        "surface": "#0f172a",
        "elevated": "#1e293b",
        "hover": "#334155",
        "accent": "#22d3ee",
        "accent_soft": "#67e8f9",
        "accent_dim": "#06b6d4",
        "gold": "#facc15",
        "success": "#10b981",
        "warning": "#f97316",
        "error": "#ef4444",
        "text": "#e2e8f0",
        "muted": "#94a3b8",
        "line": "#334155",
        "line_hover": "#475569",
        "score_excellent": "#22d3ee",
        "score_good": "#10b981",
        "score_fair": "#f97316",
        "score_poor": "#ef4444",
    },
    # ---- Studio expansion set (creative / professional colorways) ----
    "ember-console": {
        "id": "ember-console",
        "name": "Ember Console",
        "group": "Studio",
        "blurb": "Warm copper console - analog desk energy",
        "bg": "#0c0704",
        "surface": _flat("#0c0704", 42, 22, 10, 0.9),
        "elevated": _flat("#0c0704", 58, 32, 14, 0.88),
        "hover": _flat("#0c0704", 78, 42, 18, 0.9),
        "accent": "#f59e0b",
        "accent_soft": "#fbbf24",
        "accent_dim": "#b45309",
        "gold": "#fdba74",
        "success": "#84cc16",
        "warning": "#fb923c",
        "error": "#f43f5e",
        "text": "#fff7ed",
        "muted": _muted("#ffedd5", 0.55),
        "line": _flat("#0c0704", 245, 158, 11, 0.22),
        "line_hover": _flat("#0c0704", 251, 191, 36, 0.38),
        "score_excellent": "#fbbf24",
        "score_good": "#f59e0b",
        "score_fair": "#fb923c",
        "score_poor": "#f43f5e",
    },
    "arctic-line": {
        "id": "arctic-line",
        "name": "Arctic Line",
        "group": "Studio",
        "blurb": "Ice-blue precision - cold mastering suite",
        "bg": "#050a10",
        "surface": _flat("#050a10", 12, 28, 48, 0.9),
        "elevated": _flat("#050a10", 18, 40, 68, 0.88),
        "hover": _flat("#050a10", 28, 56, 92, 0.9),
        "accent": "#7dd3fc",
        "accent_soft": "#bae6fd",
        "accent_dim": "#0284c7",
        "gold": "#e2e8f0",
        "success": "#67e8f9",
        "warning": "#fcd34d",
        "error": "#fb7185",
        "text": "#f0f9ff",
        "muted": _muted("#e0f2fe", 0.5),
        "line": _flat("#050a10", 125, 211, 252, 0.2),
        "line_hover": _flat("#050a10", 186, 230, 253, 0.35),
        "score_excellent": "#bae6fd",
        "score_good": "#7dd3fc",
        "score_fair": "#fcd34d",
        "score_poor": "#fb7185",
    },
    "rosewood-suite": {
        "id": "rosewood-suite",
        "name": "Rosewood Suite",
        "group": "Studio",
        "blurb": "Deep rosewood & blush - boutique studio luxury",
        "bg": "#0a0508",
        "surface": _flat("#0a0508", 40, 14, 28, 0.9),
        "elevated": _flat("#0a0508", 56, 20, 40, 0.88),
        "hover": _flat("#0a0508", 76, 28, 52, 0.9),
        "accent": "#f472b6",
        "accent_soft": "#f9a8d4",
        "accent_dim": "#be185d",
        "gold": "#fcd34d",
        "success": "#c4b5fd",
        "warning": "#fb923c",
        "error": "#fb7185",
        "text": "#fdf2f8",
        "muted": _muted("#fce7f3", 0.52),
        "line": _flat("#0a0508", 244, 114, 182, 0.24),
        "line_hover": _flat("#0a0508", 249, 168, 212, 0.4),
        "score_excellent": "#f9a8d4",
        "score_good": "#f472b6",
        "score_fair": "#fcd34d",
        "score_poor": "#fb7185",
    },
    "jade-master": {
        "id": "jade-master",
        "name": "Jade Master",
        "group": "Studio",
        "blurb": "Jade green mastering desk - calm technical authority",
        "bg": "#040a08",
        "surface": _flat("#040a08", 8, 36, 28, 0.9),
        "elevated": _flat("#040a08", 12, 52, 40, 0.88),
        "hover": _flat("#040a08", 18, 70, 54, 0.9),
        "accent": "#34d399",
        "accent_soft": "#6ee7b7",
        "accent_dim": "#059669",
        "gold": "#a3e635",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "error": "#f87171",
        "text": "#ecfdf5",
        "muted": _muted("#d1fae5", 0.5),
        "line": _flat("#040a08", 52, 211, 153, 0.22),
        "line_hover": _flat("#040a08", 110, 231, 183, 0.38),
        "score_excellent": "#6ee7b7",
        "score_good": "#34d399",
        "score_fair": "#fbbf24",
        "score_poor": "#f87171",
    },
    "champagne-noir": {
        "id": "champagne-noir",
        "name": "Champagne Noir",
        "group": "Studio",
        "blurb": "Champagne gold on noir - executive listening room",
        "bg": "#080806",
        "surface": _flat("#080806", 28, 26, 18, 0.92),
        "elevated": _flat("#080806", 42, 38, 26, 0.9),
        "hover": _flat("#080806", 58, 52, 34, 0.9),
        "accent": "#e8c872",
        "accent_soft": "#f5e6b8",
        "accent_dim": "#a88b3a",
        "gold": "#f0d78c",
        "success": "#86efac",
        "warning": "#fbbf24",
        "error": "#f87171",
        "text": "#faf6eb",
        "muted": _muted("#f5e6b8", 0.48),
        "line": _flat("#080806", 232, 200, 114, 0.2),
        "line_hover": _flat("#080806", 245, 230, 184, 0.36),
        "score_excellent": "#f5e6b8",
        "score_good": "#e8c872",
        "score_fair": "#fbbf24",
        "score_poor": "#f87171",
    },
}

# Analyzer product default per brand matrix
DEFAULT_SKIN = "artifact-scan"

# Stable order for menus
SKIN_ORDER = [
    "artifact-scan",
    "obsidian-glass",
    "newton-antigravity",
    "chromatic-nihilism",
    "crystal-prism",
    "liquid-logic",
    "nodaw-cyber",
    "ember-console",
    "arctic-line",
    "rosewood-suite",
    "jade-master",
    "champagne-noir",
]


# Design tokens beyond color - each brand must feel different
_DESIGN_BASE: dict[str, Any] = {
    "font_family": '"Segoe UI Variable", "Segoe UI", system-ui, sans-serif',
    "font_display": '"Bahnschrift", "Segoe UI", sans-serif',
    "font_mono": '"Cascadia Code", "Consolas", monospace',
    "type_body": 13,
    "type_h1": 24,
    "type_h2": 18,
    "type_caption": 11,
    "type_display_xl": 48,
    "space_scale": 1.0,
    "radius_scale": 1.0,
    "sidebar_width": 204,
    "ring_size": 160,
    "density": "comfortable",  # compact | comfortable | airy
    "product_tag": "CORE ANALYZER",
    "hero_title": "",
    "hero_sub": "",
    "score_label": "OVERALL MIX SCORE",
    "overline_tracking": "1.4px",
    "title_tracking": "-0.3px",
    "button_radius": 6,
    "card_radius": 8,
    # Frame language: hud | glass | soft | hard | prism | liquid | cyber
    "card_shape": "glass",
    # Primary control language: solid | outline | hud | dual | soft | liquid | cyber
    "button_style": "solid",
    "card_shadow": 28,
    "show_extra_metrics": True,
    "show_deep_readout": True,
    "charts_wf_weight": 3,
    "charts_sp_weight": 2,
}

_DESIGN_OVERRIDES: dict[str, dict[str, Any]] = {
    "artifact-scan": {
        "font_family": '"Cascadia Code", "Consolas", "Segoe UI", monospace',
        "font_display": '"Cascadia Code", "Bahnschrift", monospace',
        "font_mono": '"Cascadia Code", "Consolas", monospace',
        "type_body": 12,
        "type_h1": 22,
        "type_caption": 10,
        "type_display_xl": 44,
        "space_scale": 0.92,
        "radius_scale": 0.55,
        "sidebar_width": 200,
        "ring_size": 148,
        "density": "compact",
        "product_tag": "RADAR · SCAN",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "TECHNICAL READINESS",
        "overline_tracking": "2px",
        "button_radius": 2,
        "card_radius": 3,
        "card_shape": "hud",
        "button_style": "hud",
        "card_shadow": 0,
    },
    "obsidian-glass": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Segoe UI Variable", "Bahnschrift", sans-serif',
        "type_body": 13,
        "type_h1": 26,
        "type_display_xl": 52,
        "space_scale": 1.05,
        "radius_scale": 1.0,
        "sidebar_width": 208,
        "ring_size": 170,
        "density": "comfortable",
        "product_tag": "OBSIDIAN",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "MIX SCORE",
        "button_radius": 4,
        "card_radius": 8,
        "card_shape": "glass",
        "button_style": "solid",
        "card_shadow": 36,
    },
    "newton-antigravity": {
        "font_family": '"Georgia", "Times New Roman", serif',
        "font_display": '"Georgia", "Palatino Linotype", serif',
        "font_mono": '"Consolas", monospace',
        "type_body": 14,
        "type_h1": 28,
        "type_h2": 20,
        "type_display_xl": 56,
        "space_scale": 1.15,
        "radius_scale": 1.2,
        "sidebar_width": 212,
        "ring_size": 180,
        "density": "airy",
        "product_tag": "ANTIGRAVITY",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "FIELD STRENGTH",
        "title_tracking": "-0.6px",
        "button_radius": 20,
        "card_radius": 18,
        "card_shape": "soft",
        "button_style": "soft",
        "card_shadow": 48,
        "charts_wf_weight": 2,
        "charts_sp_weight": 2,
    },
    "chromatic-nihilism": {
        "font_family": '"Impact", "Arial Black", "Segoe UI", sans-serif',
        "font_display": '"Impact", "Arial Black", sans-serif',
        "font_mono": '"Consolas", monospace',
        "type_body": 13,
        "type_h1": 30,
        "type_h2": 20,
        "type_caption": 11,
        "type_display_xl": 58,
        "space_scale": 0.88,
        "radius_scale": 0.35,
        "sidebar_width": 200,
        "ring_size": 154,
        "density": "compact",
        "product_tag": "NIHILISM",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "DAMAGE INDEX",
        "overline_tracking": "2.4px",
        "button_radius": 0,
        "card_radius": 0,
        "card_shape": "hard",
        "button_style": "dual",
        "card_shadow": 0,
        "show_deep_readout": True,
    },
    "crystal-prism": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Segoe UI Light", "Segoe UI", sans-serif',
        "type_body": 13,
        "type_h1": 27,
        "type_display_xl": 54,
        "space_scale": 1.1,
        "radius_scale": 1.15,
        "sidebar_width": 208,
        "ring_size": 172,
        "density": "airy",
        "product_tag": "PRISM",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "CLARITY",
        "button_radius": 10,
        "card_radius": 14,
        "card_shape": "prism",
        "button_style": "outline",
        "card_shadow": 32,
        "charts_wf_weight": 3,
        "charts_sp_weight": 1,
    },
    "liquid-logic": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Bahnschrift", "Segoe UI", sans-serif',
        "font_mono": '"Cascadia Code", "Consolas", monospace',
        "type_body": 12,
        "type_h1": 23,
        "type_caption": 10,
        "type_display_xl": 46,
        "space_scale": 0.95,
        "radius_scale": 0.85,
        "sidebar_width": 200,
        "ring_size": 156,
        "density": "compact",
        "product_tag": "LIQUID LOGIC",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "SIGNAL SCORE",
        "overline_tracking": "1.8px",
        "button_radius": 5,
        "card_radius": 6,
        "card_shape": "liquid",
        "button_style": "liquid",
        "card_shadow": 20,
    },
    "nodaw-cyber": {
        "font_family": '"Segoe UI", system-ui, sans-serif',
        "font_display": '"Bahnschrift", "Segoe UI", sans-serif',
        "font_mono": '"Consolas", monospace',
        "type_body": 13,
        "type_h1": 24,
        "type_display_xl": 50,
        "space_scale": 1.0,
        "radius_scale": 0.75,
        "sidebar_width": 204,
        "ring_size": 162,
        "density": "comfortable",
        "product_tag": "CYBER-HUD",
        "hero_title": "",
        "hero_sub": "",
        "score_label": "SYSTEM SCORE",
        "button_radius": 3,
        "card_radius": 4,
        "card_shape": "cyber",
        "button_style": "cyber",
        "card_shadow": 16,
    },
    "ember-console": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Bahnschrift", "Segoe UI", sans-serif',
        "type_body": 13,
        "type_h1": 25,
        "type_display_xl": 50,
        "space_scale": 1.0,
        "radius_scale": 0.9,
        "sidebar_width": 204,
        "ring_size": 164,
        "density": "comfortable",
        "product_tag": "EMBER DESK",
        "score_label": "CONSOLE SCORE",
        "overline_tracking": "1.6px",
        "button_radius": 5,
        "card_radius": 7,
        "card_shape": "glass",
        "button_style": "solid",
        "card_shadow": 30,
    },
    "arctic-line": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Segoe UI Light", "Segoe UI", sans-serif',
        "font_mono": '"Cascadia Code", "Consolas", monospace',
        "type_body": 13,
        "type_h1": 26,
        "type_display_xl": 52,
        "space_scale": 1.05,
        "radius_scale": 1.05,
        "sidebar_width": 206,
        "ring_size": 168,
        "density": "comfortable",
        "product_tag": "ARCTIC LINE",
        "score_label": "PRECISION SCORE",
        "button_radius": 6,
        "card_radius": 10,
        "card_shape": "soft",
        "button_style": "outline",
        "card_shadow": 28,
    },
    "rosewood-suite": {
        "font_family": '"Georgia", "Segoe UI", serif',
        "font_display": '"Georgia", "Palatino Linotype", serif',
        "type_body": 13,
        "type_h1": 26,
        "type_display_xl": 52,
        "space_scale": 1.08,
        "radius_scale": 1.15,
        "sidebar_width": 208,
        "ring_size": 170,
        "density": "airy",
        "product_tag": "ROSEWOOD",
        "score_label": "SUITE SCORE",
        "title_tracking": "-0.4px",
        "button_radius": 12,
        "card_radius": 14,
        "card_shape": "soft",
        "button_style": "soft",
        "card_shadow": 40,
    },
    "jade-master": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Bahnschrift", "Segoe UI", sans-serif',
        "font_mono": '"Cascadia Code", "Consolas", monospace',
        "type_body": 12,
        "type_h1": 24,
        "type_caption": 10,
        "type_display_xl": 48,
        "space_scale": 0.96,
        "radius_scale": 0.8,
        "sidebar_width": 202,
        "ring_size": 158,
        "density": "compact",
        "product_tag": "JADE MASTER",
        "score_label": "MASTER SCORE",
        "overline_tracking": "1.8px",
        "button_radius": 4,
        "card_radius": 5,
        "card_shape": "hud",
        "button_style": "hud",
        "card_shadow": 12,
    },
    "champagne-noir": {
        "font_family": '"Segoe UI Variable", "Segoe UI", sans-serif',
        "font_display": '"Segoe UI Semibold", "Bahnschrift", sans-serif',
        "type_body": 13,
        "type_h1": 27,
        "type_display_xl": 54,
        "space_scale": 1.08,
        "radius_scale": 1.1,
        "sidebar_width": 208,
        "ring_size": 172,
        "density": "airy",
        "product_tag": "CHAMPAGNE",
        "score_label": "LISTENING SCORE",
        "button_radius": 8,
        "card_radius": 12,
        "card_shape": "glass",
        "button_style": "solid",
        "card_shadow": 36,
    },
}


def _merge_design(skin: dict[str, Any]) -> dict[str, Any]:
    out = dict(skin)
    design = dict(_DESIGN_BASE)
    design.update(_DESIGN_OVERRIDES.get(skin.get("id", ""), {}))
    out.update(design)
    return out


# Attach design tokens to every skin (colors stay skin-specific)
for _sid in list(SKINS.keys()):
    SKINS[_sid] = _merge_design(SKINS[_sid])


def get_skin(skin_id: str | None) -> dict[str, Any]:
    if skin_id and skin_id in SKINS:
        return SKINS[skin_id]
    return SKINS[DEFAULT_SKIN]


def list_skins() -> list[dict[str, Any]]:
    return [SKINS[k] for k in SKIN_ORDER if k in SKINS]

