# -*- coding: utf-8 -*-
"""Engine/reports/report_generator.py — HTML + JSON report generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ..utils.file_utils import save_json

HTML_TEMPLATE = """<!doctype html>
<html lang="en" data-theme="obsidian-glass">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} | NoDAW Engine</title>
<style>
:root {{ --nd-bg-deep:#020617; --nd-cyan:#22d3ee; --nd-emerald:#10b981; --nd-orange:#f97316; --nd-red:#ef4444; --nd-text-primary:#e2e8f0; --nd-text-muted:#64748b; --nd-border:rgba(51,65,85,0.5); }}
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:'JetBrains Mono',monospace; background:var(--nd-bg-deep); color:var(--nd-text-primary); padding:40px; }}
h1 {{ font-size:24px; margin-bottom:8px; letter-spacing:-0.5px; }}
.meta {{ color:var(--nd-text-muted); font-size:12px; margin-bottom:32px; }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:12px; margin-bottom:24px; }}
.card {{ background:rgba(15,23,42,0.92); border:1px solid var(--nd-border); border-radius:8px; padding:16px; }}
.card .label {{ font-size:10px; color:var(--nd-text-muted); text-transform:uppercase; letter-spacing:0.5px; }}
.card .value {{ font-size:18px; font-weight:700; margin-top:4px; }}
.grade {{ font-size:32px; font-weight:700; }}
.score-good {{ color:var(--nd-emerald); }} .score-warn {{ color:var(--nd-orange); }} .score-bad {{ color:var(--nd-red); }}
.score-ace {{ color:var(--nd-cyan); }}
.badge {{ display:inline-block; padding:2px 8px; border-radius:4px; font-size:9px; font-weight:700; text-transform:uppercase; }}
.badge-flag {{ background:rgba(239,68,68,0.15); color:var(--nd-red); margin:2px; }}
pre {{ font-size:11px; color:var(--nd-text-muted); white-space:pre-wrap; margin-top:8px; }}
h2 {{ font-size:14px; color:var(--nd-text-muted); text-transform:uppercase; letter-spacing:0.5px; margin:24px 0 12px; }}
.penalty-bar {{ height:6px; border-radius:3px; margin-top:4px; background:rgba(255,255,255,0.06); }}
.penalty-fill {{ height:100%; border-radius:3px; }}
</style>
</head><body>
<h1>{title}</h1>
<p class="meta">{subtitle}</p>
<div class="grid">
<div class="card"><div class="label">Score</div><div class="value {score_class}">{score}</div></div>
<div class="card"><div class="label">Grade</div><div class="value grade {grade_class}">{grade}</div></div>
<div class="card"><div class="label">Restoration</div><div class="value">{restoration}</div></div>
<div class="card"><div class="label">LUFS</div><div class="value">{lufs}</div></div>
<div class="card"><div class="label">Peak</div><div class="value">{peak} dBTP</div></div>
<div class="card"><div class="label">Clipping</div><div class="value">{clipping}</div></div>
<div class="card"><div class="label">Noise Floor</div><div class="value">{noise_floor} dB</div></div>
<div class="card"><div class="label">Crest</div><div class="value">{crest} dB</div></div>
</div>
<h2>Module Scores</h2>
<div class="grid">{module_scores}</div>
<h2>Issues ({flag_count})</h2>
<p>{flags}</p>
<h2>Recommendations</h2>
<ul style="font-size:12px;color:var(--nd-text-primary);padding-left:20px">{recs}</ul>
<h2>Penalties</h2>
<pre>{penalties_json}</pre>
<p class="meta" style="margin-top:40px">Generated by NoDAW Engine LUX v3 on {timestamp}</p>
</body></html>"""


def generate_html(analysis: dict, title: str = "Quality Analysis Report") -> str:
    score = analysis.get("score", 0)
    grade = analysis.get("grade", "?")
    sc_cls = "score-good" if score >= 85 else "score-warn" if score >= 60 else "score-bad"
    gr_cls = "score-ace" if grade in ("A+", "A") else "score-good" if grade == "B" else "score-warn"
    sd = analysis.get("scoring_detail", {})
    restoration = sd.get("restoration_potential", "unknown")

    mod_scores = sd.get("module_scores", {})
    mod_html = "".join(
        f'<div class="card"><div class="label">{k}</div><div class="value">{v}</div></div>'
        for k, v in mod_scores.items()
    )

    flags = analysis.get("issue_flags", [])
    flag_html = " ".join(f'<span class="badge badge-flag">{f}</span>' for f in flags)

    recs = analysis.get("recommendations", [])
    rec_html = "".join(f"<li>{r}</li>" for r in recs)

    import datetime
    ts = datetime.datetime.now().isoformat()

    return HTML_TEMPLATE.format(
        title=title,
        subtitle=f"File: {analysis.get('_file', 'unknown')}",
        score=score, score_class=sc_cls,
        grade=grade, grade_class=gr_cls,
        restoration=restoration,
        lufs=analysis.get("lufs", "--"),
        peak=analysis.get("peak_db", "--"),
        clipping=analysis.get("clipping_events", 0),
        noise_floor=analysis.get("noise_floor_db", "--"),
        crest=analysis.get("crest_db", "--"),
        module_scores=mod_html,
        flag_count=len(flags),
        flags=flag_html,
        recs=rec_html,
        penalties_json="",
        timestamp=ts,
    )


def generate_report(analysis: dict, output_dir: Path, stem: str):
    save_json(output_dir / f"{stem}_analysis.json", analysis)
    html = generate_html(analysis, f"Analysis Report - {stem}")
    (output_dir / f"{stem}_report.html").write_text(html, encoding="utf-8")


def generate_html_report_path(output_html: Path, analysis: dict, title: str = "Repair Report") -> str:
    """Generate and write an HTML report to the given path, return the path as string."""
    html = HTML_TEMPLATE.format(
        title=title,
        subtitle=f"Post-repair analysis",
        score=analysis.get("score", 0),
        score_class="score-good" if analysis.get("score", 0) >= 85 else "score-warn",
        grade=analysis.get("grade", "?"),
        grade_class="score-ace",
        restoration="",
        lufs=analysis.get("lufs", "--"),
        peak=analysis.get("peak_db", "--"),
        clipping=analysis.get("clipping_events", 0),
        noise_floor=analysis.get("noise_floor_db", "--"),
        crest=analysis.get("crest_db", "--"),
        module_scores="",
        flag_count=len(analysis.get("issue_flags", [])),
        flags=" ".join(f'<span class="badge badge-flag">{f}</span>' for f in analysis.get("issue_flags", [])),
        recs="".join(f"<li>{r}</li>" for r in analysis.get("recommendations", [])),
        penalties_json="",
        timestamp=__import__("datetime").datetime.now().isoformat(),
    )
    output_html.parent.mkdir(parents=True, exist_ok=True)
    output_html.write_text(html, encoding="utf-8")
    return str(output_html)
